// <auto-generated />
using EFCoreDemo3.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCoreDemo3.Migrations.Student
{
    [DbContext(typeof(StudentContext))]
    partial class StudentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFCoreDemo3.Models.StudentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Course")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Fees")
                        .HasColumnType("int");

                    b.Property<string>("SName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tblStudents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Course = "Java",
                            Fees = 18000,
                            SName = "John Doe"
                        },
                        new
                        {
                            Id = 2,
                            Course = "Python",
                            Fees = 25000,
                            SName = "Jane Smith"
                        },
                        new
                        {
                            Id = 5,
                            Course = "React",
                            Fees = 25000,
                            SName = "Nithin"
                        },
                        new
                        {
                            Id = 6,
                            Course = "Angular",
                            Fees = 25000,
                            SName = "Rohit"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
